id: vesper-desktop
name: Vesper's Vanilla Desktop

stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main
    singlelayer: false
    labels:
      maintainer: Maurício Braz
    args:
      DEBIAN_FRONTEND: noninteractive

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
        - apt update && apt install -y build-essential clang cmake ninja-build \
          dconf-cli gnome-settings-daemon automake autoconf libtool pkg-config make gcc g++ \
          gdb binutils coreutils findutils diffutils gawk sed grep tar gzip bzip2 xz-utils \
          unzip zip p7zip-full rsync file man-db less tree htop ncdu curl wget git sudo \
          nano vim gnupg lsb-release apt-utils software-properties-common \
          ca-certificates locales tzdata

    modules:
      - name: init-setup
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update

      # Put your custom actions below this comment
      # Put your custom actions below this comment

      - name: install-warp
        type: includes
        includes:
          - modules/50-install-warp.yml

      - name: install-docker
        type: includes
        includes:
          - modules/86-install-docker.yml

      - name: install-gnome
        type: includes
        includes:
          - modules/86-install-gnome.yml

      - name: install-howdy
        type: includes
        includes:
          - modules/86-install-howdy.yml

      - name: install-onepassword
        type: includes
        includes:
          - modules/86-install-onepassword.yml

      - name: flatpak
        type: flatpak
        system:
          reponame: "flathub"
          repourl: "https://flathub.org/repo/flathub.flatpakrepo"
          install:
            - "com.obsproject.Studio"
            - "org.gtk.Gtk3theme.adw-gtk3"
            - "com.github.wwmm.easyeffects"
            - "org.gtk.Gtk3theme.adw-gtk3-dark"
            - "com.obsproject.Studio.Plugin.DroidCam"
          remove:
            - "com.obsproject.Studio"
            - "org.gtk.Gtk3theme.adw-gtk3"
            - "com.github.wwmm.easyeffects"
            - "org.gtk.Gtk3theme.adw-gtk3-dark"
            - "com.obsproject.Studio.Plugin.DroidCam"

      # Put your custom actions above this comment
      # Put your custom actions above this comment

      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/99-set-image-abroot-config.yml

      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - name: fsguard
        type: fsguard
        GenerateKey: true
        CustomFsGuard: false
        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"
        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup2
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
          - rm -rf /sources
